; ============================================================
; Projeto: Estação de Ar Quente SMD
; Ambiente: PlatformIO + Arduino Framework
; ============================================================

[platformio]
default_envs = ch32

; ============================================================
; ===================== STM32F103 ============================
; ============================================================

[env:stm32]
platform = ststm32
board = bluepill_f103c8
framework = arduino

; Velocidade serial (debug)
monitor_speed = 115200

; Bibliotecas utilizadas
lib_deps =
    QuickPID
    olikraus/U8g2

; Flags de compilação
build_flags =
    -I include
    -Os
    -ffunction-sections
    -fdata-sections
    -Wl,--gc-sections

; Upload via ST-Link (recomendado)
upload_protocol = stlink

; ============================================================
; ===================== CH32V203 =============================
; ============================================================

[env:ch32]
platform = https://github.com/Community-PIO-CH32V/platform-ch32v.git
board = genericCH32V203C8T6
framework = arduino

monitor_speed = 115200

lib_deps =
    QuickPID
    olikraus/U8g2

; Dependendo do core, pode precisar ajustar:
build_flags =
    -I include
    -Wall
    -D SYSCLK_FREQ_144MHz
    -D SYSCLK_FREQ_144MHz_HSI

upload_protocol = wlink